# Generated by Django 5.1.4 on 2025-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_restaurant_options_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('restaurants', models.ManyToManyField(to='core.restaurant')),
            ],
        ),
    ]
